use crate::{db::Database, domain::class::{ClassDto,ClassInput}, error::{AppError,AppResult}};
use rusqlite::{params,OptionalExtension};
use uuid::Uuid;

pub struct ClassRepository<'a>{pub db:&'a Database}
impl ClassRepository<'_>{
 pub fn list(&self,include_deleted:bool)->AppResult<Vec<ClassDto>>{self.db.read(|c|{let sql=if include_deleted{"SELECT id,name,display_order,status FROM classes ORDER BY display_order,name"}else{"SELECT id,name,display_order,status FROM classes WHERE deleted_at IS NULL ORDER BY display_order,name"};let mut s=c.prepare(sql)?;let rows=s.query_map([],|r|Ok(ClassDto{id:r.get(0)?,name:r.get(1)?,display_order:r.get(2)?,status:r.get(3)?}))?;Ok(rows.collect::<Result<Vec<_>,_>>()?)})}
 pub fn create(&self,input:ClassInput)->AppResult<ClassDto>{let name=input.name.trim();if name.is_empty(){return Err(AppError::Validation("ক্লাসের নাম প্রয়োজন।".into()));}let id=Uuid::new_v4().to_string();self.db.transaction(|tx|{let order:i64=tx.query_row("SELECT COALESCE(MAX(display_order),-1)+1 FROM classes WHERE deleted_at IS NULL",[],|r|r.get(0))?;tx.execute("INSERT INTO classes(id,name,display_order,status,created_at,updated_at) VALUES(?1,?2,?3,'active',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now'))",params![id,name,order])?;Ok(ClassDto{id:id.clone(),name:name.into(),display_order:order,status:"active".into()})})}
 pub fn rename(&self,id:&str,name:&str)->AppResult<ClassDto>{let name=name.trim();if name.is_empty(){return Err(AppError::Validation("ক্লাসের নাম প্রয়োজন।".into()));}self.db.transaction(|tx|{let changed=tx.execute("UPDATE classes SET name=?2,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?1 AND deleted_at IS NULL",params![id,name])?;if changed==0{return Err(AppError::Validation("ক্লাস পাওয়া যায়নি।".into()));}let order:i64=tx.query_row("SELECT display_order FROM classes WHERE id=?1",[id],|r|r.get(0))?;Ok(ClassDto{id:id.into(),name:name.into(),display_order:order,status:"active".into()})})}
 pub fn reorder(&self,ids:&[String])->AppResult<()>{self.db.transaction(|tx|{for(i,id)in ids.iter().enumerate(){tx.execute("UPDATE classes SET display_order=?2,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?1 AND deleted_at IS NULL",params![id,i as i64])?;}Ok(())})}
 pub fn soft_delete(&self,id:&str)->AppResult<()> {self.db.transaction(|tx|{let students:i64=tx.query_row("SELECT COUNT(*) FROM students WHERE class_id=?1 AND deleted_at IS NULL",[id],|r|r.get(0))?;if students>0{return Err(AppError::Validation(format!("এই ক্লাসে {} জন শিক্ষার্থী আছে। প্রথমে তাদের সরান।",students)));}let changed=tx.execute("UPDATE classes SET deleted_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?1 AND deleted_at IS NULL",[id])?;if changed==0{return Err(AppError::Validation("ক্লাস পাওয়া যায়নি।".into()));}Ok(())})}
 pub fn id_by_name(&self,name:&str)->AppResult<Option<String>>{self.db.read(|c|Ok(c.query_row("SELECT id FROM classes WHERE name=?1 COLLATE NOCASE AND deleted_at IS NULL",[name],|r|r.get(0)).optional()?))}
}
